---
title: "STAT 550 Course Calendar"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
  pdf_document:
    toc: false
    toc_depth: '2'
---

Homework assignments, project instructions, lecture notes and handouts will be posted in Canvas. Readings will be denoted by "550" for the _Course Notes: Statistics 550 Advanced Mathematical Statistics_ and by "505" for _A Pair of Primers: Primer on Matrix Analysis and Primer on Linear Statistical Models_. Topics on calendar are subject to change.

# Week 1: Jan 13, 15

__Reading__:  

* Course syllabus and Canvas exploration
* 505: Chapters 2 and 7, Sections 8.1-8.4 and 8.11
* 550: Chapter 2


#### _Tuesday_

* Introductions to the course and to each other
* [Spot the math errors](https://skullsinthestars.com/2008/12/12/spot-the-math-errors/)
* Deep dive into matrix algebra


#### _Thursday_ 

* Kronecker products and the vec operator

---

# Week 2: Jan 20, 22

#### _Tuesday_

* Kronecker products and the vec operator (cont)


#### _Thursday_ 

* Application of matrix operations in linear models 
* **Homework 1 Due in class**

---

# Week 3: Jan 27, 29

__Reading__:  

* 505: Chapter 12
* 550: Chapter 3

#### _Tuesday_

* Matrix differentiation

#### _Thursday_ 

* Matrix differentiation (cont)
* **Quiz 1: Matrix operations, Kronecker products, Vec**

---

# Week 4: Feb 3, 5

__Reading__:  

* 505: Chapter 9, Chapter 11 (skim), Section 15.1
* 550: Chapter 5


#### _Tuesday_

* Matrix differentiation (cont)
* Minimizing SSE from a projection operator perspective


#### _Thursday_ 

* Eigenvalue/eigenvector review
* Order of magnitude
* **Homework 2 Due in class**

---

# Week 5: Jan 10, 12

__Reading__:  

* 505: Sections 13.1-13.4
* 550: Chapters 4 and 7
* Sections 5.5.1-5.5.3 in Casella and Berger


#### _Tuesday_

* Types of convergence in probability 
* Order of magnitude in probability

#### _Thursday_ 

* Multivariate Taylor series expansions
* Newton-Raphson and Fisher Scoring algorithms
* **Quiz 2: Matrix differentiation and matrix representation of linear models**

---

# Week 6: Feb 17, 19

#### _Tuesday_

* Newton-Raphson and Fisher Scoring algorithms for logistic regression


#### _Thursday_ 

* Missing data and the EM algorithm

---

# Week 7: Feb 24, 26

#### _Tuesday_

* _No class_: Either attend the CLS Teaching Workshop with Dr. James Lang (registration required) or spend this time working on your project.
* **Project: Journal article proposal due in Canvas by 5pm**

#### _Thursday_ 

* Missing data and the EM algorithm (cont)

---

# Week 8: Mar 3, 5

#### _Tuesday_

* TBD

#### _Thursday_ 

* TBD

---

# Week 9: Mar 10, 12

#### _Tuesday_

* TBD

#### _Thursday_ 

* TBD

---

# Spring break: Mar 16-20

---

# Week 10: Mar 24, 26

#### _Tuesday_

* TBD

#### _Thursday_ 

* TBD

---

# Week 11: Mar 31, Apr 2

#### _Tuesday_

* **Project: Executive summary due in Canvas by 5pm**

#### _Thursday_ 

* TBD

---

# Week 12: Apr 7, 9

#### _Tuesday_

* TBD

#### _Thursday_ 

* TBD

---

# Week 13: Apr 14, 16

#### _Tuesday_

* **Project: Proof sketch due in Canvas by 5pm**

#### _Thursday_ 

* TBD

---

# Week 14: Apr 21, 23

#### _Tuesday_

* TBD

#### _Thursday_ 

* TBD

---

# Week 15: Apr 28, 30

**Project: Presentation slides due in Canvas by 5pm on _Monday_**


#### _Tuesday_

* Project presentations

#### _Thursday_ 

* Project presentations


---

# Finals week

* Final exam in Wilson Hall 1-128 on **Tuesday, May 5, 8:00am-9:50am**
